### Working with numpy

In [1]:
import numpy as np

In [3]:
np?

In [6]:
a=np.array([1,2,3,4,5])
print(a,type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
print(a.shape)

(5,)


In [8]:
b=np.array([[1],[2],[3],[4],[5]])

In [9]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
print(b.shape)  # 5 rows 1 cols

(5, 1)


In [12]:
b[2][0]=10

In [13]:
b

array([[ 1],
       [ 2],
       [10],
       [ 4],
       [ 5]])

In [15]:
c=np.array([[1,2,3],[4,5,6]])
print(c)


[[1 2 3]
 [4 5 6]]


In [16]:
print(c.shape)

(2, 3)


In [17]:
print(c[1][1])

5


In [18]:
# create Zeros , Ones , Custom array

In [19]:
a= np.zeros((3,3))
print(a,type(a))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] <class 'numpy.ndarray'>


In [21]:
b=np.ones((3,3))
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [24]:
c=np.full((3,2),5)   # array of some constant.
                        #frst paramater is shape (tuple)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [27]:
# identity matrix -- Square matrix
d=np.eye(4)
print(d)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [29]:
# Random Matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)


[[ 0.72341974  0.04708804  0.04868476]
 [ 0.82783208  0.86591511  0.67972037]]


In [30]:
np.random.random?

In [31]:
randomMatrix[:,2]

array([ 0.04868476,  0.67972037])

In [34]:
randomMatrix[1,1:3]=1
randomMatrix

array([[ 0.72341974,  0.04708804,  0.04868476],
       [ 0.82783208,  1.        ,  1.        ]])

In [39]:
z=np.zeros((3,3),dtype="int64")
print(z)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [41]:
 #datatypes
print(z.dtype)

int64


In [46]:
# Mathamatical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[6,7]])
print(x)

[[1 2]
 [3 4]]


In [47]:
print(y)

[[5 6]
 [6 7]]


In [48]:
print(x+y)

[[ 6  8]
 [ 9 11]]


In [50]:
np.add(x,y)

array([[ 6,  8],
       [ 9, 11]])

In [51]:
x-y

array([[-4, -4],
       [-3, -3]])

In [52]:
np.subtract(x,y)

array([[-4, -4],
       [-3, -3]])

In [53]:
x*y

array([[ 5, 12],
       [18, 28]])

In [54]:
np.multiply(x,y)

array([[ 5, 12],
       [18, 28]])

In [55]:
x/y

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.57142857]])

In [56]:
np.divide(x,y)

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.57142857]])

In [57]:
x

array([[1, 2],
       [3, 4]])

In [58]:
y

array([[5, 6],
       [6, 7]])

In [59]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [60]:
x**0.5

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [61]:
# Matrix Multiplication
x.dot(y)

array([[17, 20],
       [39, 46]])

In [62]:
np.dot(x,y)

array([[17, 20],
       [39, 46]])

In [91]:
#Multiplication Of Vectors-- Dot Product ->Scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [92]:
np.sum(a)

10

In [93]:
sum(a)

10

In [94]:
x

array([[1, 2],
       [3, 4]])

In [95]:
np.sum(x)

10

In [96]:
sum(x)

array([4, 6])

In [97]:
x

array([[1, 2],
       [3, 4]])

In [98]:
np.sum(x,axis=0)

array([4, 6])

In [99]:
np.sum(x,axis=1)

array([3, 7])

In [100]:
# Stacking of array
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [101]:
b=b**2
print(b)

[ 1  4  9 16]


In [102]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [103]:
np.stack((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [104]:
a+2

array([3, 4, 5, 6])

In [105]:
a

array([1, 2, 3, 4])

In [106]:
b

array([ 1,  4,  9, 16], dtype=int32)

In [108]:
# Reshape a numpy array
c=np.stack((a,b),axis=0)
c

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [110]:
c=c.reshape((4,2))
c

array([[ 1,  2],
       [ 3,  4],
       [ 1,  4],
       [ 9, 16]])

In [112]:
c=c.reshape((2,4))
c

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [114]:
c=c.reshape((8,1))
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 1],
       [ 4],
       [ 9],
       [16]])

In [116]:
c=c.reshape((8,))
c

array([ 1,  2,  3,  4,  1,  4,  9, 16])

In [119]:
c=c.reshape((-1,4))  # -1 means automatically calculate ...
c

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

### Numpy random modules

- rand : Random values in a given shape
- randn : Return a sample (or samples) from the 'standard normal' distribution
- randint : Return random integers from low (inclusive) to high(exclusive)
- random  : returns random floats in the range(0.0 to 1.0)
- choice : Generates a random sample from a given 1-d array
- shuffle : shuffles the contents of sequence

In [120]:
a=np.arange(10)

In [121]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.random.shuffle(a)

In [127]:
a

array([8, 9, 5, 7, 6, 4, 1, 2, 0, 3])

In [129]:
b= np.random.rand(2,3)
print(b)

[[ 0.30396559  0.87504369  0.52136501]
 [ 0.55903573  0.30172104  0.6868254 ]]


In [154]:
x=np.random.randn(2,3)
print(x)

[[ 0.74077634 -0.32896666 -0.13648271]
 [ 0.0045753  -1.67435911 -0.64300716]]


In [146]:
c=np.random.randint(1,2)  # in numpy [a,b)
print(c)

1


In [139]:
import random as r

In [145]:
r.randint(1,2) # in this both are included [a,b]

1

In [152]:
d=np.random.randint(5,20,3)
print(d)



[ 8 15 16]


In [158]:
# randomly pick one element from a array
element= np.random.choice([1,2,3,4,5])
print(element)

2


In [166]:
# Concept of seed -- pesudo random numbers 
np.random.seed(1)
np.random.randint(10,20)

15

### Some more numpy functions - statistics
  - min,max
  - mean
  - median 
  - average
  - variance
  - standard deviation

In [175]:
a=np.array([[1,2,3,4],[5,16,0,8]])
print(a)

[[ 1  2  3  4]
 [ 5 16  0  8]]


In [176]:
print(np.min(a))

0


In [177]:
print(np.min(a,axis=0)) # specify axis for the direction

[1 2 0 4]


In [178]:
print(np.min(a,axis=1))

[1 0]


In [180]:
# mean, average at the elements
b=np.array([1,2,3,4,5])
print(sum(b)/5)

3.0


In [187]:
print(a)
np.mean(a)

[[ 1  2  3  4]
 [ 5 16  0  8]]


4.875

In [188]:
np.mean(a,axis=0)

array([ 3. ,  9. ,  1.5,  6. ])

In [189]:
np.mean(a,axis=1)

array([ 2.5 ,  7.25])

In [191]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))

2.0
2.4


In [196]:
# Mean vs average -- average is weighted mean..

#w=[1,2,3,4,5]  # no difference
w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.06666666667


In [204]:
# Standard deviation-- how to compute ?
print(c)
u=np.mean(c)
mystd= np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

# inbuilt function--
s= np.std(c)
print(s)

[1 5 4 2 0]
1.8547236991
1.8547236991


In [205]:
# variance
print(mystd**2)
print(np.var(c))

3.44
3.44


In [206]:
# given a running stream of numbers,
# compute mean and variance at any given point

# n-item mean m , v
# n+1 th item x
# now mean = (n *m + x)/ (n+1)
# variance =  sum_of(x)**2 - (mean)**2
# v_old= (x1**2 + x2**2 + ... xn** 2) /(n) - m**2
# v'= ((v + m**2 )*n+ x**2 )/(n+1) - ((n*m+x)/(n+1))**2

# keep it simple :)
# just maintain 3 variables sum, sum*2,N


In [207]:
n=int(input())
sum=0
sum2=0
for i in range(n):
    num=int(input())
    sum+=num
    sum2+= (num**2)
    mean= sum/(i+1)
    var= sum2/(i+1)- mean
    print(mean,var)

10
2
2.0 2.0
3
2.5 4.0
4
3.0 6.666666666666666
2
2.75 5.5
3
2.8 5.6000000000000005
4
3.0 6.666666666666666
4
3.142857142857143 7.428571428571429
4
3.25 8.0
4
3.3333333333333335 8.444444444444445
4
3.4 8.799999999999999


In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  2 10:35:42 2018

@author: snjum
"""

import numpy as np
a=np.array([[1,2,3,4,5],[2,4,6,8,9]])
print(a)
print(a.shape,a.size,a.dtype)


print(a[0][1] , a[0,1] )
print(a[1,:])


#print(a[:3])
print(a[:,3])


print(a.sum()) # print the sum of all the elemnets
print(a.sum(axis=0)) # print the sum of elements column wise
print(a.sum(axis=1)) # print the sum of elements rowwise

print(np.exp(a))
print(np.exp(a[0,0]))
print(np.sqrt(a))
print(np.square(a))

print(np.transpose(a))


# 
c=np.zeros((3,5))
print(c)

d=np.ones((3,4),dtype=np.int16)
print(d)

e=np.eye(4,4)
print(e)

f=np.arange(10,20,2)
print(f)

g=np.arange(12).reshape(4,3)
h=np.arange(2,3,4)
print(h)

j=np.array([20,30,40,50])
h=np.arange(4)
print(j-h)
print(j+h)
print(j*h)

a=np.array([[1,2],[3,4]])
b=np.array([[0,1],[1,1]])
print(a*b)
print(a.dot(b))
print(np.dot(a,b))


a=np.random.random((2,3))
print(a)

b=np.random.randint(0,5,(2,2))
print(b)

k=np.array([[1,3],[2,4],[3,5],[4,8]])
print(k)

k1=k.reshape(2,4)
print(k1)

m=k.ravel()
print(m)


h=np.array([5.5,5.7,6.2,6.5])
w=np.array([55,50,70,75])

bmi=w/(h*h)
print(bmi)

import cv2





[[1 2 3 4 5]
 [2 4 6 8 9]]
(2, 5) 10 int32
2 2
[2 4 6 8 9]
[4 8]
44
[ 3  6  9 12 14]
[15 29]
[[  2.71828183e+00   7.38905610e+00   2.00855369e+01   5.45981500e+01
    1.48413159e+02]
 [  7.38905610e+00   5.45981500e+01   4.03428793e+02   2.98095799e+03
    8.10308393e+03]]
2.71828182846
[[ 1.          1.41421356  1.73205081  2.          2.23606798]
 [ 1.41421356  2.          2.44948974  2.82842712  3.        ]]
[[ 1  4  9 16 25]
 [ 4 16 36 64 81]]
[[1 2]
 [2 4]
 [3 6]
 [4 8]
 [5 9]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[10 12 14 16 18]
[2]
[20 29 38 47]
[20 31 42 53]
[  0  30  80 150]
[[0 2]
 [3 4]]
[[2 3]
 [4 7]]
[[2 3]
 [4 7]]
[[ 0.64828826  0.73566189  0.9812865 ]
 [ 0.43277536  0.9633254   0.58568925]]
[[3 0]
 [2 3]]
[[1 3]
 [2 4]
 [3 5]
 [4 8]]
[[1 3 2 4]
 [3 5 4 8]]
[1 3 2 4 3 5 4 8]
[ 1.81818182  1.53893506  1.82101977  1.77514793]
